//! UAX #9 Unicode Bidirectional Algorithm (Unicode 16): pure, std only.
//!
//! One *paragraph* per `analyze` call (split text at hard line breaks first:
//! `text_wrap.Line.hard_break`). `analyze` resolves embedding levels for the
//! whole paragraph (P2-P3, X1-X10 incl. isolates, W1-W7, N0 bracket pairs,
//! N1-N2, I1-I2); the per-line steps work on the wrapped line ranges:
//!
//!   - `lineLevels`   L1 (trailing whitespace / separators reset to the paragraph level)
//!   - `lineRuns`     L2 visual order as runs `{start, end, level}` (byte offsets)
//!   - `visualOrder`  L2 on a plain level array (code points or clusters)
//!   - `caretMove`    left/right arrow in *visual* order (word jumps stay logical:
//!                    the existing `unicode.nextWordBoundary` is already logical)
//!   - `selectionSpans` highlight x-ranges for a logical selection on one line
//!
//! Characters removed by X9 (explicit embeddings/overrides, BN) keep the level
//! of their predecessor so they never split a run; `Analysis.isRemoved` tells.
//! Property data comes from `unicode_tables.zig` (generated by
//! `tools/gen_unicode.zig`). L3/L4 (combining marks, mirroring glyphs) are the
//! renderer's job: `mirrored` gives the bracket mirror for rtl runs.

const std = @import("std");
const unicode = @import("unicode.zig");
const t = @import("unicode_tables.zig");

/// Bidi_Class. Order matches `tools/gen_unicode.zig`.
pub const Class = enum(u8) { l, r, al, en, es, et, an, cs, nsm, bn, b, s, ws, on, lre, lro, rle, rlo, pdf, lri, rli, fsi, pdi };

/// Paragraph direction request.
pub const Direction = enum { auto, ltr, rtl };

/// Maximum explicit embedding depth (BD2).
pub const MAX_DEPTH = 125;
const MAX_BRACKET_STACK = 63;

pub fn classOf(cp: u21) Class {
    return @fromBackingInt(@intCast(t.lookup(&t.bidi_runs, cp)));
}

fn bracketEntry(cp: u21) ?u64 {
    var lo: usize = 0;
    var hi: usize = t.bidi_brackets.len;
    while (lo < hi) {
        const mid = (lo + hi) / 2;
        const k: u21 = @intCast(t.bidi_brackets[mid] & 0x1FFFFF);
        if (k == cp) return t.bidi_brackets[mid];
        if (k < cp) lo = mid + 1 else hi = mid;
    }
    return null;
}

/// The paired bracket of `cp` (its mirror image in rtl runs), if `cp` is one.
pub fn mirrored(cp: u21) ?u21 {
    const e = bracketEntry(cp) orelse return null;
    return @intCast((e >> 21) & 0x1FFFFF);
}

fn canonBracket(cp: u21) u21 {
    return switch (cp) {
        0x2329 => 0x3008,
        0x232A => 0x3009,
        else => cp,
    };
}

/// True for classes X9 removes from the text.
pub fn isRemovedClass(c: Class) bool {
    return switch (c) {
        .lre, .lro, .rle, .rlo, .pdf, .bn => true,
        else => false,
    };
}

/// Result of resolving one paragraph. All slices are per code point except
/// `offsets` (code points + 1 byte offsets, the last is `text.len`).
pub const Analysis = struct {
    para_level: u8,
    /// Resolved embedding level per code point (before L1).
    levels: []u8,
    /// Original Bidi_Class per code point.
    classes: []Class,
    offsets: []u32,

    pub fn deinit(self: Analysis, gpa: std.mem.Allocator) void {
        gpa.free(self.levels);
        gpa.free(self.classes);
        gpa.free(self.offsets);
    }

    pub fn len(self: Analysis) usize {
        return self.levels.len;
    }

    pub fn isRemoved(self: Analysis, i: usize) bool {
        return isRemovedClass(self.classes[i]);
    }

    /// Index of the code point that starts at or after byte offset `byte`.
    pub fn cpIndexAt(self: Analysis, byte: usize) usize {
        var lo: usize = 0;
        var hi: usize = self.offsets.len - 1;
        while (lo < hi) {
            const mid = (lo + hi) / 2;
            if (self.offsets[mid] < byte) lo = mid + 1 else hi = mid;
        }
        return lo;
    }

    /// True when the whole paragraph is one left-to-right run at level 0
    /// (the renderer can skip all bidi work).
    pub fn isPlainLtr(self: Analysis) bool {
        if (self.para_level != 0) return false;
        for (self.levels) |l| if (l != 0) return false;
        return true;
    }
};

const Stack = struct {
    const Entry = struct { level: u8, override: ?Class, isolate: bool };
    items: [MAX_DEPTH + 2]Entry = undefined,
    n: usize = 0,
    fn push(s: *Stack, e: Entry) void {
        s.items[s.n] = e;
        s.n += 1;
    }
    fn pop(s: *Stack) void {
        s.n -= 1;
    }
    fn top(s: *const Stack) Entry {
        return s.items[s.n - 1];
    }
};

fn isIsolateInit(c: Class) bool {
    return c == .lri or c == .rli or c == .fsi;
}

fn isStrong(c: Class) bool {
    return c == .l or c == .r or c == .al;
}

/// P2/P3 over `classes[from..to]`, skipping isolates. 0, 1, or null when no strong.
fn firstStrongLevel(classes: []const Class, match_pdi: []const u32, from: usize, to: usize) ?u8 {
    var i = from;
    while (i < to) : (i += 1) {
        switch (classes[i]) {
            .l => return 0,
            .r, .al => return 1,
            .lri, .rli, .fsi => {
                if (match_pdi[i] == NONE) return null;
                i = match_pdi[i];
            },
            else => {},
        }
    }
    return null;
}

const NONE = std.math.maxInt(u32);

/// Resolve the embedding levels of one paragraph of UTF-8 `text`.
pub fn analyze(gpa: std.mem.Allocator, text: []const u8, dir: Direction) !Analysis {
    // Decode.
    var n: usize = 0;
    {
        var p: usize = 0;
        while (p < text.len) : (n += 1) p += unicode.utf8DecodeLossy(text, p).len;
    }
    const offsets = try gpa.alloc(u32, n + 1);
    errdefer gpa.free(offsets);
    const ocls = try gpa.alloc(Class, n);
    errdefer gpa.free(ocls);
    const levels = try gpa.alloc(u8, n);
    errdefer gpa.free(levels);
    var cps = try gpa.alloc(u21, n);
    defer gpa.free(cps);
    {
        var p: usize = 0;
        var i: usize = 0;
        while (p < text.len) : (i += 1) {
            const d = unicode.utf8DecodeLossy(text, p);
            offsets[i] = @intCast(p);
            cps[i] = d.cp;
            ocls[i] = classOf(d.cp);
            p += d.len;
        }
        offsets[n] = @intCast(text.len);
    }

    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    // BD9: matching PDI for each isolate initiator (and back).
    const match_pdi = try arena.alloc(u32, n);
    const match_init = try arena.alloc(u32, n);
    @memset(match_pdi, NONE);
    @memset(match_init, NONE);
    {
        var stack: std.ArrayList(u32) = .empty;
        for (ocls, 0..) |c, i| {
            if (isIsolateInit(c)) {
                try stack.append(arena, @intCast(i));
            } else if (c == .pdi) {
                if (stack.pop()) |o| {
                    match_pdi[o] = @intCast(i);
                    match_init[i] = o;
                }
            }
        }
    }

    // P2/P3.
    const para_level: u8 = switch (dir) {
        .ltr => 0,
        .rtl => 1,
        .auto => firstStrongLevel(ocls, match_pdi, 0, n) orelse 0,
    };

    // X1-X8. `cls` is the working class (overrides applied).
    const cls = try arena.dupe(Class, ocls);
    {
        var st: Stack = .{};
        st.push(.{ .level = para_level, .override = null, .isolate = false });
        var overflow_iso: usize = 0;
        var overflow_emb: usize = 0;
        var valid_iso: usize = 0;
        for (0..n) |i| {
            const c = ocls[i];
            switch (c) {
                .rle, .lre, .rlo, .lro => {
                    levels[i] = st.top().level;
                    const rtl = c == .rle or c == .rlo;
                    const cur = st.top().level;
                    const nl: u8 = if (rtl) (cur + 1) | 1 else (cur + 2) & ~@as(u8, 1);
                    if (nl <= MAX_DEPTH and overflow_iso == 0 and overflow_emb == 0) {
                        st.push(.{
                            .level = nl,
                            .override = switch (c) {
                                .rlo => Class.r,
                                .lro => Class.l,
                                else => null,
                            },
                            .isolate = false,
                        });
                    } else if (overflow_iso == 0) overflow_emb += 1;
                },
                .rli, .lri, .fsi => {
                    levels[i] = st.top().level;
                    if (st.top().override) |o| cls[i] = o;
                    var rtl = c == .rli;
                    if (c == .fsi) {
                        const end = if (match_pdi[i] != NONE) match_pdi[i] else n;
                        rtl = (firstStrongLevel(ocls, match_pdi, i + 1, end) orelse 0) == 1;
                    }
                    const cur = st.top().level;
                    const nl: u8 = if (rtl) (cur + 1) | 1 else (cur + 2) & ~@as(u8, 1);
                    if (nl <= MAX_DEPTH and overflow_iso == 0 and overflow_emb == 0) {
                        valid_iso += 1;
                        st.push(.{ .level = nl, .override = null, .isolate = true });
                    } else overflow_iso += 1;
                },
                .pdi => {
                    if (overflow_iso > 0) {
                        overflow_iso -= 1;
                    } else if (valid_iso > 0) {
                        overflow_emb = 0;
                        while (!st.top().isolate) st.pop();
                        st.pop();
                        valid_iso -= 1;
                    }
                    levels[i] = st.top().level;
                    if (st.top().override) |o| cls[i] = o;
                },
                .pdf => {
                    levels[i] = st.top().level;
                    if (overflow_iso > 0) {} else if (overflow_emb > 0) {
                        overflow_emb -= 1;
                    } else if (!st.top().isolate and st.n >= 2) {
                        st.pop();
                    }
                },
                .b => levels[i] = para_level,
                .bn => levels[i] = st.top().level,
                else => {
                    levels[i] = st.top().level;
                    if (st.top().override) |o| cls[i] = o;
                },
            }
        }
    }

    const explicit = try arena.dupe(u8, levels); // sos/eos use these, not resolved levels

    // X9 + X10: non-removed indices, level runs, isolating run sequences.
    var idx: std.ArrayList(u32) = .empty;
    for (0..n) |i| if (!isRemovedClass(ocls[i])) try idx.append(arena, @intCast(i));
    const m = idx.items.len;

    const LvRun = struct { s: u32, e: u32 }; // positions in `idx`, [s, e)
    var runs: std.ArrayList(LvRun) = .empty;
    const run_of = try arena.alloc(u32, n); // char index -> run
    {
        var s: usize = 0;
        while (s < m) {
            var e = s + 1;
            while (e < m and levels[idx.items[e]] == levels[idx.items[s]]) e += 1;
            for (s..e) |k| run_of[idx.items[k]] = @intCast(runs.items.len);
            try runs.append(arena, .{ .s = @intCast(s), .e = @intCast(e) });
            s = e;
        }
    }

    var seq: std.ArrayList(u32) = .empty; // char indices of the current sequence
    for (runs.items) |r0| {
        const first_char = idx.items[r0.s];
        if (ocls[first_char] == .pdi and match_init[first_char] != NONE) continue; // continues an earlier sequence
        seq.clearRetainingCapacity();
        var r = r0;
        while (true) {
            for (r.s..r.e) |k| try seq.append(arena, idx.items[k]);
            const last_char = idx.items[r.e - 1];
            if (isIsolateInit(ocls[last_char]) and match_pdi[last_char] != NONE and !isRemovedClass(ocls[match_pdi[last_char]])) {
                r = runs.items[run_of[match_pdi[last_char]]];
            } else break;
        }
        try resolveSequence(arena, seq.items, cps, ocls, cls, levels, explicit, idx.items, r0.s, r.e, para_level, n);
    }

    // Removed characters take the level of their predecessor (para level first).
    {
        var prev: u8 = para_level;
        for (0..n) |i| {
            if (isRemovedClass(ocls[i])) levels[i] = prev else prev = levels[i];
        }
    }

    return .{ .para_level = para_level, .levels = levels, .classes = ocls, .offsets = offsets };
}

/// Resolve W1-W7, N0-N2, I1-I2 for one isolating run sequence `seq` (char
/// indices). `first_pos`/`last_end` are the positions in `idx` of the first
/// run's start and the last run's end, used for sos/eos.
fn resolveSequence(
    arena: std.mem.Allocator,
    seq: []const u32,
    cps: []const u21,
    ocls: []const Class,
    cls: []Class,
    levels: []u8,
    explicit: []const u8,
    idx: []const u32,
    first_pos: u32,
    last_end: u32,
    para_level: u8,
    n_total: usize,
) !void {
    _ = n_total;
    const lvl = levels[seq[0]];
    const prev_level: u8 = if (first_pos > 0) explicit[idx[first_pos - 1]] else para_level;
    const last_char = seq[seq.len - 1];
    const next_level: u8 = if (isIsolateInit(ocls[last_char]) or last_end >= idx.len) para_level else explicit[idx[last_end]];
    const sos: Class = if (@max(lvl, prev_level) & 1 == 1) .r else .l;
    const eos: Class = if (@max(lvl, next_level) & 1 == 1) .r else .l;
    const e_dir: Class = if (lvl & 1 == 1) .r else .l;

    const k = seq.len;
    const c = try arena.alloc(Class, k);
    for (seq, 0..) |ci, j| c[j] = cls[ci];

    // W1
    for (0..k) |j| {
        if (c[j] == .nsm) {
            const prev: Class = if (j == 0) sos else c[j - 1];
            c[j] = if (isIsolateInit(prev) or prev == .pdi) .on else prev;
        }
    }
    // W2, W3
    {
        var last_strong: Class = sos;
        for (0..k) |j| {
            switch (c[j]) {
                .l, .r, .al => last_strong = c[j],
                .en => if (last_strong == .al) {
                    c[j] = .an;
                },
                else => {},
            }
        }
        for (0..k) |j| if (c[j] == .al) {
            c[j] = .r;
        };
    }
    // W4
    for (1..@max(k, 2) - 1) |j| {
        if (c[j] == .es and c[j - 1] == .en and c[j + 1] == .en) {
            c[j] = .en;
        } else if (c[j] == .cs and c[j - 1] == .en and c[j + 1] == .en) {
            c[j] = .en;
        } else if (c[j] == .cs and c[j - 1] == .an and c[j + 1] == .an) {
            c[j] = .an;
        }
    }
    // W5
    {
        var j: usize = 0;
        while (j < k) {
            if (c[j] != .et) {
                j += 1;
                continue;
            }
            var e = j;
            while (e < k and c[e] == .et) e += 1;
            const adj = (j > 0 and c[j - 1] == .en) or (e < k and c[e] == .en);
            if (adj) for (j..e) |q| {
                c[q] = .en;
            };
            j = e;
        }
    }
    // W6
    for (0..k) |j| if (c[j] == .es or c[j] == .et or c[j] == .cs) {
        c[j] = .on;
    };
    // W7
    {
        var last_strong: Class = sos;
        for (0..k) |j| {
            switch (c[j]) {
                .l, .r => last_strong = c[j],
                .en => if (last_strong == .l) {
                    c[j] = .l;
                },
                else => {},
            }
        }
    }
    // N0
    {
        const Pair = struct { o: u32, c: u32 };
        var pairs: std.ArrayList(Pair) = .empty;
        var stack: [MAX_BRACKET_STACK]struct { close: u21, pos: u32 } = undefined;
        var sn: usize = 0;
        scan: for (0..k) |j| {
            if (c[j] != .on) continue;
            const cp = cps[seq[j]];
            const ent = bracketEntry(cp) orelse continue;
            const is_close = (ent >> 42) & 1 == 1;
            const pair_cp: u21 = @intCast((ent >> 21) & 0x1FFFFF);
            if (!is_close) {
                if (sn == MAX_BRACKET_STACK) break :scan;
                stack[sn] = .{ .close = canonBracket(pair_cp), .pos = @intCast(j) };
                sn += 1;
            } else {
                const want = canonBracket(cp);
                var s = sn;
                while (s > 0) {
                    s -= 1;
                    if (stack[s].close == want) {
                        try pairs.append(arena, .{ .o = stack[s].pos, .c = @intCast(j) });
                        sn = s;
                        break;
                    }
                }
            }
        }
        std.mem.sort(Pair, pairs.items, {}, struct {
            fn lt(_: void, a: Pair, b: Pair) bool {
                return a.o < b.o;
            }
        }.lt);
        for (pairs.items) |pr| {
            var found_e = false;
            var found_o = false;
            for (pr.o + 1..pr.c) |q| {
                const d = strongOf(c[q]) orelse continue;
                if (d == e_dir) found_e = true else found_o = true;
            }
            var resolved: ?Class = null;
            if (found_e) {
                resolved = e_dir;
            } else if (found_o) {
                var ctx: Class = sos;
                var q = pr.o;
                while (q > 0) {
                    q -= 1;
                    if (strongOf(c[q])) |d| {
                        ctx = d;
                        break;
                    }
                }
                resolved = if (ctx != e_dir) ctx else e_dir;
            }
            if (resolved) |rc| {
                for ([2]u32{ pr.o, pr.c }) |bp| {
                    c[bp] = rc;
                    var q = bp + 1;
                    while (q < k and ocls[seq[q]] == .nsm) : (q += 1) c[q] = rc;
                }
            }
        }
    }
    // N1, N2
    {
        var j: usize = 0;
        while (j < k) {
            if (!isNeutral(c[j])) {
                j += 1;
                continue;
            }
            var e = j;
            while (e < k and isNeutral(c[e])) e += 1;
            const before: Class = if (j == 0) sos else strongOf(c[j - 1]) orelse e_dir;
            const after: Class = if (e == k) eos else strongOf(c[e]) orelse e_dir;
            const rc: Class = if (before == after) before else e_dir;
            for (j..e) |q| c[q] = rc;
            j = e;
        }
    }
    // I1, I2
    for (0..k) |j| {
        const ci = seq[j];
        if (lvl & 1 == 0) {
            switch (c[j]) {
                .r => levels[ci] = lvl + 1,
                .an, .en => levels[ci] = lvl + 2,
                else => levels[ci] = lvl,
            }
        } else {
            switch (c[j]) {
                .l, .en, .an => levels[ci] = lvl + 1,
                else => levels[ci] = lvl,
            }
        }
    }
}

/// Strong direction for N0/N1 (EN and AN count as R); null for neutrals.
fn strongOf(c: Class) ?Class {
    return switch (c) {
        .l => .l,
        .r, .en, .an => .r,
        else => null,
    };
}

fn isNeutral(c: Class) bool {
    return switch (c) {
        .b, .s, .ws, .on, .fsi, .lri, .rli, .pdi => true,
        else => false,
    };
}

// ── Per-line steps ─────────────────────────────────────────────────

/// L1 for the line `[start, end)` (byte offsets, e.g. `text_wrap.Line.start` and
/// `.hang`): separators and trailing whitespace / isolate controls get the
/// paragraph level. `out` must hold one level per code point of the line;
/// returns the filled prefix.
pub fn lineLevels(an: Analysis, start: usize, end: usize, out: []u8) []u8 {
    const a = an.cpIndexAt(start);
    const b = an.cpIndexAt(end);
    const n = b - a;
    std.debug.assert(out.len >= n);
    @memcpy(out[0..n], an.levels[a..b]);
    var reset = true; // scanning backward inside a trailing whitespace sequence
    var i = n;
    while (i > 0) {
        i -= 1;
        const c = an.classes[a + i];
        switch (c) {
            .b, .s => {
                out[i] = an.para_level;
                reset = true;
            },
            .ws, .fsi, .lri, .rli, .pdi => {
                if (reset) out[i] = an.para_level;
            },
            else => if (isRemovedClass(c)) {
                if (reset) out[i] = an.para_level;
            } else {
                reset = false;
            },
        }
    }
    return out[0..n];
}

/// L2: `order[v]` = index (into `levels`) of the unit shown at visual slot `v`.
/// `order.len` must equal `levels.len`. Units are code points or clusters.
pub fn visualOrder(levels: []const u8, order: []u32) void {
    std.debug.assert(order.len == levels.len);
    for (order, 0..) |*o, i| o.* = @intCast(i);
    if (levels.len == 0) return;
    var highest: u8 = 0;
    var lowest_odd: u8 = 255;
    for (levels) |l| {
        highest = @max(highest, l);
        if (l & 1 == 1) lowest_odd = @min(lowest_odd, l);
    }
    if (lowest_odd == 255) return;
    var lv = highest;
    while (lv >= lowest_odd) : (lv -= 1) {
        var i: usize = 0;
        while (i < levels.len) {
            if (levels[order[i]] < lv) {
                i += 1;
                continue;
            }
            var e = i;
            while (e < levels.len and levels[order[e]] >= lv) e += 1;
            std.mem.reverse(u32, order[i..e]);
            i = e;
        }
        if (lv == 0) break;
    }
}

/// One directional run of a line, in visual order. `start`/`end` are byte
/// offsets into the paragraph text; odd `level` runs are drawn right to left.
pub const Run = struct { start: u32, end: u32, level: u8 };

/// L1 + L2 for the line `[start, end)`: runs left to right as displayed.
/// Caller owns the returned slice.
pub fn lineRuns(gpa: std.mem.Allocator, an: Analysis, start: usize, end: usize) ![]Run {
    const a = an.cpIndexAt(start);
    const b = an.cpIndexAt(end);
    const n = b - a;
    var out: std.ArrayList(Run) = .empty;
    errdefer out.deinit(gpa);
    if (n == 0) return out.toOwnedSlice(gpa);
    const lv = try gpa.alloc(u8, n);
    defer gpa.free(lv);
    _ = lineLevels(an, start, end, lv);
    const order = try gpa.alloc(u32, n);
    defer gpa.free(order);
    visualOrder(lv, order);
    var v: usize = 0;
    while (v < n) {
        const first = order[v];
        const level = lv[first];
        var e = v + 1;
        while (e < n and lv[order[e]] == level) {
            const step: i64 = if (level & 1 == 1) -1 else 1;
            if (@as(i64, order[e]) != @as(i64, order[e - 1]) + step) break;
            e += 1;
        }
        const lo = @min(order[v], order[e - 1]);
        const hi = @max(order[v], order[e - 1]);
        try out.append(gpa, .{ .start = an.offsets[a + lo], .end = an.offsets[a + hi + 1], .level = level });
        v = e;
    }
    return out.toOwnedSlice(gpa);
}

// ── Clusters on a line: caret and selection ────────────────────────

/// Direction of an arrow key.
pub const Arrow = enum { left, right };

/// Grapheme clusters of a line with their levels (L1 applied) and visual order.
const Clusters = struct {
    start: []u32,
    level: []u8,
    order: []u32, // visual slot -> logical cluster
    end: u32,

    fn init(gpa: std.mem.Allocator, text: []const u8, an: Analysis, start: usize, end: usize) !Clusters {
        const a = an.cpIndexAt(start);
        const b = an.cpIndexAt(end);
        const cp_lv = try gpa.alloc(u8, b - a);
        defer gpa.free(cp_lv);
        _ = lineLevels(an, start, end, cp_lv);
        var count: usize = 0;
        var p = start;
        while (p < end) : (count += 1) p = @min(unicode.nextGrapheme(text[0..end], p), end);
        const cs = try gpa.alloc(u32, count);
        errdefer gpa.free(cs);
        const cl = try gpa.alloc(u8, count);
        errdefer gpa.free(cl);
        const order = try gpa.alloc(u32, count);
        errdefer gpa.free(order);
        p = start;
        for (0..count) |k| {
            cs[k] = @intCast(p);
            cl[k] = cp_lv[an.cpIndexAt(p) - a];
            p = @min(unicode.nextGrapheme(text[0..end], p), end);
        }
        visualOrder(cl, order);
        return .{ .start = cs, .level = cl, .order = order, .end = @intCast(end) };
    }

    fn deinit(self: Clusters, gpa: std.mem.Allocator) void {
        gpa.free(self.start);
        gpa.free(self.level);
        gpa.free(self.order);
    }

    fn clusterEnd(self: Clusters, k: usize) u32 {
        return if (k + 1 < self.start.len) self.start[k + 1] else self.end;
    }

    /// Caret on the visual left / right edge of cluster `k`.
    fn leftEdge(self: Clusters, k: usize) Caret {
        return if (self.level[k] & 1 == 1) .{ .index = self.clusterEnd(k), .trailing = true } else .{ .index = self.start[k], .trailing = false };
    }
    fn rightEdge(self: Clusters, k: usize) Caret {
        return if (self.level[k] & 1 == 1) .{ .index = self.start[k], .trailing = false } else .{ .index = self.clusterEnd(k), .trailing = true };
    }

    fn visualIndex(self: Clusters, k: usize) usize {
        for (self.order, 0..) |o, v| if (o == k) return v;
        unreachable;
    }

    fn clusterAt(self: Clusters, byte: u32) usize {
        var k: usize = 0;
        while (k + 1 < self.start.len and self.start[k + 1] <= byte) k += 1;
        return k;
    }

    /// Visual slot (0 = left edge of the line, n = right edge) of a caret.
    fn slotOf(self: Clusters, c: Caret) usize {
        if (self.start.len == 0) return 0;
        const trailing = c.trailing or c.index >= self.end;
        if (trailing and c.index > self.start[0]) {
            const k = self.clusterAt(@intCast(c.index - 1));
            return self.visualIndex(k) + @intFromBool(self.level[k] & 1 == 0);
        }
        const k = self.clusterAt(@intCast(c.index));
        return self.visualIndex(k) + @intFromBool(self.level[k] & 1 == 1);
    }
};

/// A logical caret plus which side of the boundary it is drawn on. At a
/// boundary between runs of different direction one logical `index` has two
/// visual positions: `trailing` selects the trailing edge of the cluster before
/// `index`, otherwise the leading edge of the cluster at `index`.
pub const Caret = struct { index: usize, trailing: bool = false };

/// Left / right arrow in visual order over the line `[start, end)`. Returns
/// the new caret, or null when it is already at that visual edge of the line
/// (the caller moves to the neighbouring line). Word jumps are logical: use
/// `unicode.nextWordBoundary` / `prevWordBoundary` unchanged.
pub fn caretMove(gpa: std.mem.Allocator, text: []const u8, an: Analysis, start: usize, end: usize, caret: Caret, arrow: Arrow) !?Caret {
    const cl = try Clusters.init(gpa, text, an, start, end);
    defer cl.deinit(gpa);
    const slot = cl.slotOf(caret);
    switch (arrow) {
        .left => {
            if (slot == 0) return null;
            return cl.leftEdge(cl.order[slot - 1]);
        },
        .right => {
            if (slot >= cl.start.len) return null;
            return cl.rightEdge(cl.order[slot]);
        },
    }
}

/// A horizontal span `[x0, x1)` in line-local pixels.
pub const Span = struct { x0: f32, x1: f32 };

/// Highlight spans for the logical selection `[sel_start, sel_end)` on the line
/// `[start, end)`. `advances[k]` is the width of the k-th grapheme cluster in
/// logical order. One span per visually contiguous selected stretch (so a
/// selection across an rtl/ltr boundary may yield several). Caller owns the slice.
pub fn selectionSpans(gpa: std.mem.Allocator, text: []const u8, an: Analysis, start: usize, end: usize, advances: []const f32, sel_start: usize, sel_end: usize) ![]Span {
    const cl = try Clusters.init(gpa, text, an, start, end);
    defer cl.deinit(gpa);
    std.debug.assert(advances.len >= cl.start.len);
    var out: std.ArrayList(Span) = .empty;
    errdefer out.deinit(gpa);
    var x: f32 = 0;
    var open: ?f32 = null;
    for (cl.order) |k| {
        const w = advances[k];
        const sel = cl.start[k] >= sel_start and cl.start[k] < sel_end;
        if (sel) {
            if (open == null) open = x;
        } else if (open) |o| {
            try out.append(gpa, .{ .x0 = o, .x1 = x });
            open = null;
        }
        x += w;
    }
    if (open) |o| try out.append(gpa, .{ .x0 = o, .x1 = x });
    return out.toOwnedSlice(gpa);
}

// ── Tests ──────────────────────────────────────────────────────────

const testing = std.testing;

test "bidi: plain latin is level 0 and plain-ltr" {
    const an = try analyze(testing.allocator, "hello world", .auto);
    defer an.deinit(testing.allocator);
    try testing.expect(an.isPlainLtr());
}

test "bidi: hebrew paragraph is rtl, digits go to level 2" {
    const an = try analyze(testing.allocator, "\u{5d0}\u{5d1} 12", .auto);
    defer an.deinit(testing.allocator);
    try testing.expectEqual(@as(u8, 1), an.para_level);
    try testing.expectEqualSlices(u8, &.{ 1, 1, 1, 2, 2 }, an.levels);
}

test "bidi: L2 reorders a mixed line into runs" {
    const text = "ab \u{5d0}\u{5d1}\u{5d2} cd";
    const an = try analyze(testing.allocator, text, .ltr);
    defer an.deinit(testing.allocator);
    const runs = try lineRuns(testing.allocator, an, 0, text.len);
    defer testing.allocator.free(runs);
    try testing.expectEqual(@as(usize, 3), runs.len);
    try testing.expectEqual(@as(u8, 1), runs[1].level);
    try testing.expectEqual(@as(u32, 3), runs[1].start);
    try testing.expectEqual(@as(u32, 9), runs[1].end);
}

test "bidi: L1 resets trailing whitespace to the paragraph level" {
    const text = "\u{5d0}  ";
    const an = try analyze(testing.allocator, text, .ltr);
    defer an.deinit(testing.allocator);
    var buf: [8]u8 = undefined;
    const lv = lineLevels(an, 0, text.len, &buf);
    try testing.expectEqualSlices(u8, &.{ 1, 0, 0 }, lv);
}

test "bidi: caret walks the visual order across an rtl run and back" {
    // a HEB1 HEB2 b: bytes a=0, HEB1 1..3, HEB2 3..5, b=5..6. Visual: a HEB2 HEB1 b.
    const text = "a\u{5d0}\u{5d1}b";
    const an = try analyze(testing.allocator, text, .ltr);
    defer an.deinit(testing.allocator);
    const g = testing.allocator;
    var c: Caret = .{ .index = 1, .trailing = true }; // right after "a"
    const expect = [_]Caret{
        .{ .index = 3, .trailing = false }, // crossed HEB2 (visually first)
        .{ .index = 1, .trailing = false }, // crossed HEB1
        .{ .index = 6, .trailing = true }, // crossed "b"
    };
    for (expect) |want| {
        c = (try caretMove(g, text, an, 0, text.len, c, .right)).?;
        try testing.expectEqual(want, c);
    }
    try testing.expectEqual(@as(?Caret, null), try caretMove(g, text, an, 0, text.len, c, .right));
    // and back to the start
    var steps: usize = 0;
    while (try caretMove(g, text, an, 0, text.len, c, .left)) |n| : (steps += 1) c = n;
    try testing.expectEqual(@as(usize, 4), steps);
    try testing.expectEqual(@as(usize, 0), c.index);
}

test "bidi: selection in an rtl run highlights one contiguous span" {
    const text = "a\u{5d0}\u{5d1}b";
    const an = try analyze(testing.allocator, text, .ltr);
    defer an.deinit(testing.allocator);
    const adv = [_]f32{ 10, 8, 8, 10 };
    // The first hebrew letter (logical 1..3) is the visually right one of the run.
    const sp = try selectionSpans(testing.allocator, text, an, 0, text.len, &adv, 1, 3);
    defer testing.allocator.free(sp);
    try testing.expectEqual(@as(usize, 1), sp.len);
    try testing.expectEqual(@as(f32, 18), sp[0].x0);
    try testing.expectEqual(@as(f32, 26), sp[0].x1);
    const all = try selectionSpans(testing.allocator, text, an, 0, text.len, &adv, 0, text.len);
    defer testing.allocator.free(all);
    try testing.expectEqual(@as(usize, 1), all.len);
    try testing.expectEqual(@as(f32, 36), all[0].x1);
}

test "bidi: brackets mirror across canonical equivalents" {
    try testing.expectEqual(@as(?u21, ')'), mirrored('('));
    try testing.expectEqual(@as(?u21, 0x232A), mirrored(0x2329));
    try testing.expectEqual(@as(?u21, null), mirrored('a'));
}

// BidiCharacterTest.txt (Unicode 16.0.0), every 300th data line (conformance excerpt).
// Fields: code points; paragraph direction (0 ltr, 1 rtl, 2 auto); resolved paragraph
// level; levels ('x' = removed by X9); visual order (removed characters omitted).
const conformance = @embedFile("testdata/BidiCharacterTest_excerpt.txt");

test "bidi: BidiCharacterTest conformance excerpt (levels + visual order)" {
    const gpa = testing.allocator;
    var lines = std.mem.splitScalar(u8, conformance, '\n');
    var checked: usize = 0;
    while (lines.next()) |raw| {
        const line = std.mem.trim(u8, raw, " \t\r");
        if (line.len == 0 or line[0] == '#') continue;
        var f = std.mem.splitScalar(u8, line, ';');
        const cps_f = f.next().?;
        const dir_f = f.next().?;
        const plevel_f = f.next().?;
        const levels_f = f.next().?;
        const order_f = f.next().?;

        var buf: [256]u8 = undefined;
        var n: usize = 0;
        var it = std.mem.tokenizeScalar(u8, cps_f, ' ');
        while (it.next()) |tok| {
            const cp = try std.fmt.parseInt(u21, tok, 16);
            n += try std.unicode.utf8Encode(cp, buf[n..]);
        }
        const text = buf[0..n];
        const dir: Direction = switch (dir_f[0]) {
            '0' => .ltr,
            '1' => .rtl,
            else => .auto,
        };
        const an = try analyze(gpa, text, dir);
        defer an.deinit(gpa);
        try testing.expectEqual(try std.fmt.parseInt(u8, plevel_f, 10), an.para_level);

        const lv = try gpa.alloc(u8, an.len());
        defer gpa.free(lv);
        _ = lineLevels(an, 0, text.len, lv);
        var li = std.mem.tokenizeScalar(u8, levels_f, ' ');
        var i: usize = 0;
        while (li.next()) |tok| : (i += 1) {
            if (tok[0] == 'x') {
                try testing.expect(an.isRemoved(i));
            } else {
                testing.expectEqual(try std.fmt.parseInt(u8, tok, 10), lv[i]) catch |e| {
                    std.debug.print("levels mismatch at cp {d} in: {s}\n", .{ i, line });
                    return e;
                };
            }
        }
        try testing.expectEqual(an.len(), i);

        const order = try gpa.alloc(u32, an.len());
        defer gpa.free(order);
        visualOrder(lv, order);
        var oi = std.mem.tokenizeScalar(u8, order_f, ' ');
        var v: usize = 0;
        while (oi.next()) |tok| {
            while (v < order.len and an.isRemoved(order[v])) v += 1;
            testing.expect(v < order.len and order[v] == try std.fmt.parseInt(u32, tok, 10)) catch |e| {
                std.debug.print("order mismatch in: {s}\n", .{line});
                return e;
            };
            v += 1;
        }
        while (v < order.len and an.isRemoved(order[v])) v += 1;
        try testing.expectEqual(order.len, v);
        checked += 1;
    }
    try testing.expect(checked > 250);
}
