#!/usr/bin/env python3
"""Generate src/text/compose_table.zig: canonical (NFC) base + combining-mark compositions.

  python3 tools/gen_compose.py > src/text/compose_table.zig

Pairs whose composite is in Latin-1/Latin Extended-A/B (U+00C0-024F), Greek (U+0370-03FF) or
Cyrillic (U+0400-04FF) and whose second code point is a combining diacritic (U+0300-036F): the
accented letters common faces ship precomposed. Vietnamese (U+1E00-1EFF) is left out to keep the
table small (about 2 KB); the shaper falls back to centring the mark glyph over the base.
Source: the canonical decompositions in Python's `unicodedata` (Unicode 14), the same data as
UnicodeData.txt field 5 (the generator for the other Unicode tables needs the UCD files, which
CI does not carry).
"""
import unicodedata as u

pairs = []
for lo, hi in ((0xC0, 0x24F), (0x370, 0x3FF), (0x400, 0x4FF)):
    for cp in range(lo, hi + 1):
        d = u.decomposition(chr(cp))
        if not d or d.startswith('<'):
            continue
        p = d.split()
        if len(p) != 2:
            continue
        base, mark = int(p[0], 16), int(p[1], 16)
        if 0x300 <= mark <= 0x36F and base < 0x500:
            pairs.append((base, mark, cp))
pairs.sort()

print("//! Generated by tools/gen_compose.py (Unicode %s): do not edit." % u.unidata_version)
print("//! Canonical compositions base + combining mark -> precomposed letter, sorted by (base, mark).")
print()
print("const std = @import(\"std\");")
print()
print("pub const Entry = struct { base: u16, mark: u16, composed: u16 };")
print()
print("pub const table = [_]Entry{")
for b, m, c in pairs:
    print("    .{ .base = 0x%04X, .mark = 0x%04X, .composed = 0x%04X }," % (b, m, c))
print("};")
print('''
/// The precomposed code point for `base` + `mark`, if one is in the table.
pub fn compose(base: u21, mark: u21) ?u21 {
    if (base > 0xFFFF or mark > 0xFFFF) return null;
    var lo: usize = 0;
    var hi: usize = table.len;
    while (lo < hi) {
        const mid = lo + (hi - lo) / 2;
        const e = table[mid];
        const order = std.math.order(@as(u32, e.base) << 16 | e.mark, @as(u32, @intCast(base)) << 16 | @as(u32, @intCast(mark)));
        switch (order) {
            .eq => return e.composed,
            .lt => lo = mid + 1,
            .gt => hi = mid,
        }
    }
    return null;
}

test "compose: common Latin, Greek and Cyrillic pairs; unrelated pairs are null" {
    try std.testing.expectEqual(@as(?u21, 0x00E9), compose('e', 0x0301));
    try std.testing.expectEqual(@as(?u21, 0x00C5), compose('A', 0x030A));
    try std.testing.expectEqual(@as(?u21, 0x00F1), compose('n', 0x0303));
    try std.testing.expectEqual(@as(?u21, 0x03AC), compose(0x03B1, 0x0301));
    try std.testing.expectEqual(@as(?u21, 0x0439), compose(0x0438, 0x0306));
    try std.testing.expectEqual(@as(?u21, null), compose('e', 0x0302 + 0x100));
    try std.testing.expectEqual(@as(?u21, null), compose('x', 0x0301));
}

test "the table is sorted and has no duplicates" {
    for (table[1..], 0..) |e, i| {
        const prev = table[i];
        try std.testing.expect((@as(u32, prev.base) << 16 | prev.mark) < (@as(u32, e.base) << 16 | e.mark));
    }
}''')
