#!/usr/bin/env python3
"""Regenerate the "Module Structure" tree in CLAUDE.md and AGENTS.md from the
files on disk (first `//!` line of each source file). Run from the repo root:

    python3 tools/gen_tree.py          # rewrite the blocks between the markers
    python3 tools/gen_tree.py --check  # exit 1 if they are stale (CI / audit)

`zig build audit` separately fails if a src/ file is missing from the block.
"""
import os, re, sys

START = "<!-- module-tree:start (generated by tools/gen_tree.py; do not edit by hand) -->"
END = "<!-- module-tree:end -->"

# Files whose first `//!` line is missing or unhelpful.
OVERRIDE = {
    "core/cmd.zig": "Cmd union, CmdBuffer + emitters, arena, validateBalance, OverlayStyle/leafMsg",
    "core/component.zig": "Components(), validateComponent, buildMsgs: comptime component stitching (hatch 1)",
    "core/dropdown.zig": "Dropdown(cap): closed button + auto-anchored overlay list (no new Cmd)",
    "core/transient.zig": "TransientState: hover/press/focus/IME/caret-phase (hatch 2)",
    "layout/engine.zig": "LayoutEngine: measure / widths / heights / position passes, ClipStack",
    "render/build.zig": "[]Cmd + []Rect + TransientState -> vertices, text/image/scene draws",
    "render/vertex.zig": "Vertex layout + quad emitters",
    "run.zig": "teak.run + Runtime(App, Host, Gpu): the canonical loop (one frame() per tick), App hooks, idle skip",
    "resources.zig": "run-loop resource table (key -> Gpu handle), stageDraws",
    "teak.zig": "public library root: every re-export, documented",
}
TOOL_OVERRIDE = {
    "gen_tree.py": "regenerates the Module Structure tree in CLAUDE.md / AGENTS.md from the files on disk",
    "gen_compose.py": "generates src/text/compose_table.zig (Unicode compose sequences)",
}

def first_line(path):
    """First sentence of the leading `//!` block (up to 5 lines joined)."""
    parts = []
    for l in open(path, errors="ignore"):
        if l.startswith("//!"):
            t = l[3:].strip()
            if t.startswith("```"):
                break
            if not t:
                if parts:
                    break
                continue
            parts.append(t)
            joined = " ".join(parts)
            if re.search(r"[.!?](\s|$)", joined) or len(parts) >= 5:
                break
        elif l.strip() and not l.startswith("//"):
            break
    t = " ".join(parts).replace("`", "")
    m = re.search(r"^(.*?[.!?])(\s|$)", t)
    return m.group(1) if m else t

def clip(t, n=96):
    t = re.sub(r"\s+", " ", t).strip()
    if len(t) > n:
        t = t[:n].rsplit(" ", 1)[0]
    return t.rstrip(".:;,- ")

def is_test(f):
    return f.endswith("_test.zig") or f.endswith("test.zig")

def src_lines():
    out = []
    for d, ds, fs in sorted(os.walk("src")):
        ds[:] = sorted(x for x in ds if x not in ("vendor", "testdata"))
        rel = os.path.relpath(d, "src")
        depth = 0 if rel == "." else rel.count(os.sep) + 1
        if rel != ".":
            out.append("  " * depth + os.path.basename(d) + "/")
        for f in sorted(fs):
            if not f.endswith(".zig") or is_test(f):
                continue
            key = f if rel == "." else os.path.join(rel, f)
            purpose = OVERRIDE.get(key) or first_line(os.path.join(d, f))
            out.append(("  " * (depth + 1) + f).ljust(46) + "-- " + clip(purpose))
    # Drop directory lines with no file under them (e.g. fonts/, test data).
    pruned = []
    for i, l in enumerate(out):
        if l.rstrip().endswith("/") and "--" not in l:
            ind = len(l) - len(l.lstrip())
            nxt = out[i + 1] if i + 1 < len(out) else ""
            if not nxt or len(nxt) - len(nxt.lstrip()) <= ind:
                continue
        pruned.append(l)
    return pruned

EXAMPLE_OVERRIDE = {
    "counter_greeter": "the proto-2 demo: composed Counter + Greeter (Components), selection + clipboard, help modal",
    "todo": "dynamic-content stress: N rows from Model.items, Msg-with-index, scroll-clipped list",
    "tree": "recursive view emission with expand/collapse over a flat pre-order node array",
}

def examples_lines():
    out = []
    for e in sorted(os.listdir("examples")):
        if not os.path.isdir(os.path.join("examples", e)):
            continue
        p = ""
        for cand in ("app.zig", "main.zig", "model.zig", "ui_main.zig"):
            fp = os.path.join("examples", e, "src", cand)
            if os.path.exists(fp) and first_line(fp):
                p = first_line(fp); break
        out.append(("  " + e + "/").ljust(46) + "-- " + clip(EXAMPLE_OVERRIDE.get(e, p)))
    return out

def simple_dir(path, exts, indent="  "):
    out = []
    for f in sorted(os.listdir(path)):
        if not f.endswith(exts) or f.startswith("_"):
            continue
        if f in TOOL_OVERRIDE:
            out.append((indent + f).ljust(46) + "-- " + TOOL_OVERRIDE[f])
            continue
        p = ""
        for l in open(os.path.join(path, f), errors="ignore"):
            m = re.match(r"\s*(//!|//|#!|#|\*|/\*)\s*(.*)", l)
            if m and m.group(2) and not m.group(2).startswith(("!", "/")):
                p = m.group(2); break
        out.append((indent + f).ljust(46) + "-- " + clip(p))
    return out

def block():
    lines = ["```", "src/                                          -- the library, consumable as a Zig module"]
    lines += src_lines()
    lines += ["", "examples/                                     -- each its own build.zig; consume teak as a module"]
    lines += examples_lines()
    lines += ["", "shaders/"] + simple_dir("shaders", (".wgsl",))
    lines += ["", "tools/"] + simple_dir("tools", (".zig", ".py", ".sh", ".mjs"))
    lines += ["```"]
    return "\n".join(lines)

def splice(path, body):
    s = open(path).read()
    new = START + "\n" + body + "\n" + END
    if START in s:
        s2 = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: new, s, flags=re.S)
    else:
        # first run: replace the first fenced block under "## Module Structure"
        i = s.index("## Module Structure")
        a = s.index("```", i)
        b = s.index("```", a + 3) + 3
        s2 = s[:a] + new + s[b:]
    return s, s2

def main():
    body = block()
    stale = False
    for path in ("CLAUDE.md", "AGENTS.md"):
        old, new = splice(path, body)
        if old != new:
            stale = True
            if "--check" not in sys.argv:
                open(path, "w").write(new)
    if "--check" in sys.argv and stale:
        print("module tree is stale: run python3 tools/gen_tree.py")
        sys.exit(1)

main()
