//! Generated API reference: walks `src/teak.zig` with `std.zig.Ast`, follows
//! each `pub const x = @import("...")` into its file, and writes every public
//! declaration's signature and `///` doc comment.
//!
//!   zig build api       regenerate docs/api.md and llms-full.txt
//!   zig build audit     fails when either file is stale (rule in audit.zig)
//!
//! `llms.txt` stays hand-curated; `llms-full.txt` is that file verbatim plus
//! the generated reference after a marker line, so an agent that wants every
//! signature reads one file and an agent that wants the narrative reads the
//! short one. Nothing generated is ever edited by hand.

const std = @import("std");
const Ast = std.zig.Ast;

pub const ROOT = "src/teak.zig";
pub const API_FILE = "docs/api.md";
pub const FULL_FILE = "llms-full.txt";
pub const LLMS_FILE = "llms.txt";
const MARKER = "<!-- GENERATED API REFERENCE BELOW: tools/gen_api.zig, do not edit -->";

pub const Out = struct {
    api: []u8,
    full: []u8,

    pub fn deinit(self: Out, gpa: std.mem.Allocator) void {
        gpa.free(self.api);
        gpa.free(self.full);
    }
};

const Import = struct { name: []const u8, path: []const u8 };

pub fn generate(gpa: std.mem.Allocator, io: std.Io) !Out {
    var arena_state = std.heap.ArenaAllocator.init(gpa);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    const root_src = try readZ(arena, io, ROOT);
    const root = try Ast.parse(arena, root_src, .{});

    // Pass 1: name -> file for every `pub const x = @import("p.zig")`.
    var imports: std.ArrayList(Import) = .empty;
    for (root.rootDecls()) |d| {
        const vd = root.fullVarDecl(d) orelse continue;
        const init_node = vd.ast.init_node.unwrap() orelse continue;
        if (importPath(root, init_node)) |p| try imports.append(arena, .{ .name = root.tokenSlice(vd.ast.mut_token + 1), .path = p });
    }

    var w: std.Io.Writer.Allocating = .init(arena);
    const o = &w.writer;
    try o.writeAll(
        \\# Teak API reference (generated)
        \\
        \\<!-- GENERATED by tools/gen_api.zig from src/teak.zig and the files it imports.
        \\     Do not edit: run `zig build api`. `zig build audit` fails when this is stale. -->
        \\
        \\Signatures and `///` doc comments of every public declaration reachable from
        \\`@import("teak")`. Hand-written guidance lives in `llms.txt` and
        \\`docs/cookbook.md`; this file is the exhaustive, always-current index.
        \\
        \\## Re-exports of `teak`
        \\
        \\
    );

    // Pass 2: the root's own public surface.
    for (root.rootDecls()) |d| {
        if (!isPub(root, d)) continue;
        const name = declName(root, d) orelse continue;
        try writeDoc(o, root, d, "");
        if (root.fullVarDecl(d)) |vd| {
            const init_node = vd.ast.init_node.unwrap() orelse continue;
            if (importPath(root, init_node)) |p| {
                try o.print("- `teak.{s}`: module `src/{s}`; see below\n", .{ name, p });
            } else if (try resolveAlias(arena, io, root, imports.items, init_node)) |r| {
                try o.print("- `teak.{s}` = `{s}`\n", .{ name, oneLine(arena, root.getNodeSource(init_node)) });
                try writeMembers(arena, o, r.tree, r.node, "  ");
            } else {
                try o.print("- `teak.{s}`: `{s}`\n", .{ name, oneLine(arena, srcOf(root, d)) });
            }
        } else {
            try o.print("- `{s}`\n", .{oneLine(arena, srcOf(root, d))});
        }
    }

    // Pass 3: one section per imported module.
    try o.writeAll("\n## Modules\n");
    for (imports.items) |imp| {
        const path = try std.fmt.allocPrint(arena, "src/{s}", .{imp.path});
        const src = readZ(arena, io, path) catch continue;
        const tree = try Ast.parse(arena, src, .{});
        try o.print("\n### `teak.{s}` (`{s}`)\n\n", .{ imp.name, path });
        try writeModuleDoc(o, tree);
        for (tree.rootDecls()) |d| {
            if (!isPub(tree, d)) continue;
            try writeDecl(arena, o, tree, d);
        }
    }

    const api = try gpa.dupe(u8, w.written());
    errdefer gpa.free(api);

    const llms = try std.Io.Dir.cwd().readFileAlloc(io, LLMS_FILE, arena, .unlimited);
    const full = try std.fmt.allocPrint(gpa, "{s}\n---\n\n{s}\n\n{s}", .{ llms, MARKER, api });
    return .{ .api = api, .full = full };
}

// ── Emitting ───────────────────────────────────────────────────────

fn writeDecl(arena: std.mem.Allocator, o: *std.Io.Writer, tree: Ast, d: Ast.Node.Index) !void {
    try writeDoc(o, tree, d, "");
    if (tree.nodeTag(d) == .fn_decl) {
        try o.print("- `{s}`\n", .{oneLine(arena, fnSig(tree, d))});
        return;
    }
    const vd = tree.fullVarDecl(d) orelse return;
    const name = tree.tokenSlice(vd.ast.mut_token + 1);
    const init_node = vd.ast.init_node.unwrap() orelse {
        try o.print("- `{s}`\n", .{oneLine(arena, srcOf(tree, d))});
        return;
    };
    if (containerKind(tree, init_node)) |kind| {
        try o.print("- `{s} {s}`\n", .{ kind, name });
        try writeMembers(arena, o, tree, init_node, "  ");
    } else if (importPath(tree, init_node) != null) {
        // module aliases inside a module are not part of its API surface
    } else {
        try o.print("- `{s}`\n", .{oneLine(arena, srcOf(tree, d))});
    }
}

/// Fields (names only) and public member signatures of a container.
fn writeMembers(arena: std.mem.Allocator, o: *std.Io.Writer, tree: Ast, node: Ast.Node.Index, indent: []const u8) !void {
    var buf: [2]Ast.Node.Index = undefined;
    const c = tree.fullContainerDecl(&buf, node) orelse return;
    var fields: std.ArrayList(u8) = .empty;
    for (c.ast.members) |m| {
        switch (tree.nodeTag(m)) {
            .container_field_init, .container_field_align, .container_field => {
                const f = tree.fullContainerField(m).?;
                if (fields.items.len > 0) try fields.appendSlice(arena, ", ");
                try fields.appendSlice(arena, tree.tokenSlice(f.ast.main_token));
            },
            else => {},
        }
    }
    if (fields.items.len > 0) {
        const shown = if (fields.items.len > 400) fields.items[0..400] else fields.items;
        try o.print("{s}- fields: `{s}{s}`\n", .{ indent, shown, if (fields.items.len > 400) ", ..." else "" });
    }
    for (c.ast.members) |m| {
        if (!isPub(tree, m)) continue;
        if (tree.nodeTag(m) == .fn_decl) {
            try writeDoc(o, tree, m, indent);
            try o.print("{s}- `{s}`\n", .{ indent, oneLine(arena, fnSig(tree, m)) });
        } else if (tree.fullVarDecl(m)) |vd| {
            // Nested public types / constants: name + kind only.
            const name = tree.tokenSlice(vd.ast.mut_token + 1);
            if (vd.ast.init_node.unwrap()) |i| {
                if (containerKind(tree, i)) |kind| {
                    try writeDoc(o, tree, m, indent);
                    try o.print("{s}- `{s} {s}`\n", .{ indent, kind, name });
                }
            }
        }
    }
}

/// Up to the first paragraph of the file's `//!` comment.
fn writeModuleDoc(o: *std.Io.Writer, tree: Ast) !void {
    var i: usize = 0;
    var lines: usize = 0;
    while (i < tree.tokens.len and tree.tokenTag(@intCast(i)) == .container_doc_comment) : (i += 1) {
        const t = tree.tokenSlice(@intCast(i));
        const body = std.mem.trim(u8, t[3..], " \r\n");
        if (body.len == 0 and lines > 0) break;
        if (body.len == 0) continue;
        try o.print("{s}\n", .{body});
        lines += 1;
        if (lines >= 6) break;
    }
    if (lines > 0) try o.writeAll("\n");
}

/// `///` lines directly above `node`.
fn writeDoc(o: *std.Io.Writer, tree: Ast, node: Ast.Node.Index, indent: []const u8) !void {
    var tok: Ast.TokenIndex = tree.firstToken(node);
    var start = tok;
    while (start > 0 and tree.tokenTag(start - 1) == .doc_comment) start -= 1;
    if (start == tok) return;
    tok = start;
    var first = true;
    while (tree.tokenTag(tok) == .doc_comment) : (tok += 1) {
        const body = std.mem.trim(u8, tree.tokenSlice(tok)[3..], " \r\n");
        if (body.len == 0) continue;
        try o.print("{s}{s}{s}\n", .{ indent, if (first) "> " else "> ", body });
        first = false;
    }
}

// ── AST helpers ────────────────────────────────────────────────────

fn isPub(tree: Ast, d: Ast.Node.Index) bool {
    const t = tree.firstToken(d);
    return tree.tokenTag(t) == .keyword_pub;
}

fn declName(tree: Ast, d: Ast.Node.Index) ?[]const u8 {
    if (tree.fullVarDecl(d)) |vd| return tree.tokenSlice(vd.ast.mut_token + 1);
    var buf: [1]Ast.Node.Index = undefined;
    if (tree.nodeTag(d) == .fn_decl) {
        const proto = tree.nodeData(d).node_and_node[0];
        if (tree.fullFnProto(&buf, proto)) |fp| if (fp.name_token) |n| return tree.tokenSlice(n);
    }
    return null;
}

fn srcOf(tree: Ast, d: Ast.Node.Index) []const u8 {
    return tree.getNodeSource(d);
}

/// Signature text of a `fn_decl`: from `pub` to the end of the return type.
fn fnSig(tree: Ast, d: Ast.Node.Index) []const u8 {
    const proto = tree.nodeData(d).node_and_node[0];
    return tree.getNodeSource(proto);
}

fn containerKind(tree: Ast, n: Ast.Node.Index) ?[]const u8 {
    var buf: [2]Ast.Node.Index = undefined;
    const c = tree.fullContainerDecl(&buf, n) orelse return null;
    return switch (tree.tokenTag(c.ast.main_token)) {
        .keyword_struct => "struct",
        .keyword_enum => "enum",
        .keyword_union => "union",
        .keyword_opaque => "opaque",
        else => null,
    };
}

/// The path of `@import("p")` when `n` is exactly that, else null.
fn importPath(tree: Ast, n: Ast.Node.Index) ?[]const u8 {
    switch (tree.nodeTag(n)) {
        .builtin_call_two, .builtin_call_two_comma => {
            if (!std.mem.eql(u8, tree.tokenSlice(tree.nodeMainToken(n)), "@import")) return null;
            const arg = tree.nodeData(n).opt_node_and_opt_node[0].unwrap() orelse return null;
            if (tree.nodeTag(arg) != .string_literal) return null;
            const s = tree.tokenSlice(tree.nodeMainToken(arg));
            const p = s[1 .. s.len - 1];
            if (std.mem.eql(u8, p, "build_options") or std.mem.eql(u8, p, "std")) return null;
            return p;
        },
        else => return null,
    }
}

const Resolved = struct { tree: Ast, node: Ast.Node.Index };

/// `alias.Name` where `alias` is a module imported by the root: the container
/// declared as `Name` in that module.
fn resolveAlias(arena: std.mem.Allocator, io: std.Io, root: Ast, imports: []const Import, n: Ast.Node.Index) !?Resolved {
    if (root.nodeTag(n) != .field_access) return null;
    const lhs, const name_tok = root.nodeData(n).node_and_token;
    if (root.nodeTag(lhs) != .identifier) return null;
    const alias = root.tokenSlice(root.nodeMainToken(lhs));
    const member = root.tokenSlice(name_tok);
    for (imports) |imp| {
        if (!std.mem.eql(u8, imp.name, alias)) continue;
        const path = try std.fmt.allocPrint(arena, "src/{s}", .{imp.path});
        const src = readZ(arena, io, path) catch return null;
        const tree = try Ast.parse(arena, src, .{});
        for (tree.rootDecls()) |d| {
            const vd = tree.fullVarDecl(d) orelse continue;
            if (!std.mem.eql(u8, tree.tokenSlice(vd.ast.mut_token + 1), member)) continue;
            const i = vd.ast.init_node.unwrap() orelse return null;
            if (containerKind(tree, i) == null) return null;
            return .{ .tree = tree, .node = i };
        }
    }
    return null;
}

/// Collapse whitespace runs so a multi-line signature is one Markdown line;
/// long initializers are cut.
fn oneLine(arena: std.mem.Allocator, s: []const u8) []const u8 {
    var out: std.ArrayList(u8) = .empty;
    var prev_space = false;
    for (s) |c| {
        const sp = c == ' ' or c == '\n' or c == '\r' or c == '\t';
        if (sp) {
            if (!prev_space) out.append(arena, ' ') catch return s;
        } else out.append(arena, if (c == '`') '\'' else c) catch return s;
        prev_space = sp;
    }
    const t = std.mem.trim(u8, out.items, " ");
    return if (t.len > 220) t[0..220] else t;
}

fn readZ(arena: std.mem.Allocator, io: std.Io, path: []const u8) ![:0]const u8 {
    const bytes = try std.Io.Dir.cwd().readFileAlloc(io, path, arena, .unlimited);
    const z = try arena.alloc(u8, bytes.len + 1);
    @memcpy(z[0..bytes.len], bytes);
    z[bytes.len] = 0;
    return z[0..bytes.len :0];
}

// ── CLI ────────────────────────────────────────────────────────────

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const out = try generate(gpa, init.io);
    defer out.deinit(gpa);
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = API_FILE, .data = out.api });
    try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = FULL_FILE, .data = out.full });
    std.debug.print("wrote {s} ({d} bytes) and {s} ({d} bytes)\n", .{ API_FILE, out.api.len, FULL_FILE, out.full.len });
}
